# 📘 Day 24: Matrices Practice Notebook

## 🎯 Objective
Understand matrices and their operations with real-world ML intuition.



## Step 1: Create Matrices

In [3]:
# TODO: Import numpy
import numpy as np
# TODO: Create a 2x2 matrix
matrix1 = np.array([[1,2], [3,4]])
# TODO: Create a 3x3 matrix
matrix2 = np.array([[1,2,3], [4,5,6], [7,8,9]])



(2, 2)
(3, 3)


**Matrix = collection of vectors**

**Each row = one data point**

**Each column = one feature**

## Step 2: Matrix Shape & Size

In [7]:
# TODO: Find shape of matrices
print('Matrix2 Shape', matrix2.shape)
# TODO: Find number of elements
num_features = matrix2.shape[1]
num_data_points = matrix2.shape[0]
num_elements = matrix2.size

print("Features:", num_features)
print("Data points:", num_data_points)
print("Total elements:", num_elements)

Matrix2 Shape (3, 3)
Features: 3
Data points: 3
Total elements: 9


## Step 3: Matrix Addition & Subtraction

In [12]:
matrix1 = np.array([[5,2,-1], [4,9,6], [7,3,9]])
matrix2 = np.array([[1,2,3], [7,-1,-6], [2,-5,6]])
# TODO: Add two matrices
add = matrix1 + matrix2
# TODO: Subtract two matrices
sub = matrix1 - matrix2

print('Addition=\n', add)
print('Subtraction=\n', sub)

Addition=
 [[ 6  4  2]
 [11  8  0]
 [ 9 -2 15]]
Subtraction=
 [[ 4  0 -4]
 [-3 10 12]
 [ 5  8  3]]


## Step 4: Scalar Multiplication

In [13]:
# TODO: Multiply matrix by a scalar
#Scalar = controls intensity of data
#Bigger → scaled up

#Fraction → scaled down

#Negative → sign flips
scalar = 2
matrix_scaled = scalar * matrix1

print('Scaled=\n', matrix_scaled)

Scaled=
 [[10  4 -2]
 [ 8 18 12]
 [14  6 18]]


## Step 5: Matrix Transpose

In [20]:
# TODO: Transpose a matrix
#  Transpose = change perspective of data
#  Rows ↔ Features swap
# Transpose is used in:

# # Matrix multiplication
# Neural networks (weights)
# Data transformation
# Linear regression

matrix1 = np.array([[1,2,3], [4,5,6]])
print(matrix1.shape)
matrix1_T = matrix1.T
print(matrix1_T.shape)
matrix1_T_another = np.transpose(matrix1)
print(matrix1_T_another.shape)
print('Before Transpose=\n', matrix1)
print('After Transpose=\n', matrix1_T)

(2, 3)
(3, 2)
(3, 2)
Before Transpose=
 [[1 2 3]
 [4 5 6]]
After Transpose=
 [[1 4]
 [2 5]
 [3 6]]


## Step 6: Indexing & Slicing

In [28]:
# TODO: Access specific element
print(matrix1[1][2])
# TODO: Access a row
# access data point
print(matrix1[1])
# TODO: Access a column
# access feature
print(matrix1[:, 2])

6
[4 5 6]
[3 6]


## 🚀 Bonus Challenge
- Represent an image as a matrix
- Modify brightness (add scalar)
- Flip matrix using transpose


### Represent an image as a matrix

In [33]:
#Image = matrix of pixel values

#Grayscale → 2D matrix

#Color → 3D matrix
from PIL import Image
import numpy as np

# Load image
img = Image.open("sample.jpg").convert('L')  # grayscale

# Convert to matrix
img_matrix = np.array(img)

print(img_matrix.shape)

(509, 769)


### Add scalar → increase brightness
### Subtract scalar → decrease brightness

In [36]:
bright_img = img_matrix + 50

# Clip values (important!)
bright_img = np.clip(bright_img, 0, 255)


# Convert back to image
Image.fromarray(bright_img.astype('uint8')).show()

### Flip Image using Transpose

In [38]:
transposed_img = img_matrix.T

Image.fromarray(transposed_img.astype('uint8')).show()