# 📘 Day 25: Matrix Multiplication

## 🎯 Objective
Understand matrix multiplication and its role in Machine Learning.

👉 Fill all TODOs yourself.


## Step 1: Create Matrices

In [3]:
# TODO: Import numpy
import numpy as np
# TODO: Create matrix A (2x3)
A = np.array([[4, 6, -3], [1, -4, 9]])

# TODO: Create matrix B (3x4)
B = np.array([[5, -2, 6, 8], [8, 3, -4, 1], [7, -1, 5, 9]])

## Step 2: Manual Matrix Multiplication (Core Understanding)

In [4]:
# TODO: Multiply A and B manually using loops
# Hint: use nested loops
# Matrix multiplication = dot product of row & column
# Neural networks = repeated matrix multiplication
# output = input @ weights
rows_A = A.shape[0]
cols_B = B.shape[1]
cols_A = A.shape[1]

print('A=\n', A)
print('B=\n', B)

result = np.array([[0 for _ in range(cols_B)] for _ in range(rows_A)])


for i in range(rows_A):
    for j in range(cols_B):
        for k in range(cols_A):
            result[i][j] += A[i][k] + B[k][j]
print('Result=\n', result)

A=
 [[ 4  6 -3]
 [ 1 -4  9]]
B=
 [[ 5 -2  6  8]
 [ 8  3 -4  1]
 [ 7 -1  5  9]]
Result=
 [[27  7 14 25]
 [26  6 13 24]]


## Step 3: NumPy Matrix Multiplication

In [5]:
# TODO: Multiply matrices using np.dot() or @ operator
# Python introduced @ specifically for matrix multiplication
#It’s not NumPy-specific
#Works across libraries (NumPy, PyTorch, etc.)
#np.dot() behaves differently for 1D, 2D, ND arrays
#@ is more consistent and predictable
result = np.dot(A, B)
result1 = A @ B
print('Result=\n', result)
print('Result=\n', result1)

Result=
 [[ 47  13 -15  11]
 [ 36 -23  67  85]]
Result=
 [[ 47  13 -15  11]
 [ 36 -23  67  85]]


## Step 4: Shape Rules

In [6]:
# TODO: Print shapes of A, B, and result
print('Shape of A= ', A.shape)
print('Shape of B= ',B.shape)
print('Shape of Result= ',result.shape)
# TODO: Verify multiplication condition
if (A.shape[1] == B.shape[0]):
    print("Multiplication is possible")
else :
    print("Multiplication is not possible")

Shape of A=  (2, 3)
Shape of B=  (3, 4)
Shape of Result=  (2, 4)
Multiplication is possible


## Step 5: Matrix × Vector

In [7]:
# TODO: Create a vector
v = np.array([2, 4, 7])

#A=
# [[ 4  6 -3]
# [ 1 -4  9]]
print('Shape of A= ', A.shape)
print('Shape of v= ',v.shape)
# TODO: Multiply matrix A with vector
result = A @ v

print('Result=', result)

Shape of A=  (2, 3)
Shape of v=  (3,)
Result= [11 49]


## Step 6: Mini Project – Neural Layer Simulation

In [22]:
# TODO: Create input vector (features)
# Real-Life Scenario: Movie Recommendation System
# Step 1: Input (User Preferences)
#[action, romance, comedy]
x = np.array([7, 5, 6])
# user like action less, romance more, comedy maximum

# TODO: Create weight matrix
#Each column = one “hidden neuron”

#Feature	Neuron 1	Neuron 2
#Action 	0	        3
#Romance	1	       -1
#Comedy	    3	        1
#Interpretation:
#Neuron 1 cares a lot about Comedy
#Neuron 2 penalizes Romance

w = np.array([[0,4], [1, -1], [3, 1]])

    
# TODO: Compute output = input @ weights

# TODO: Add bias
# Bias adjusts:Overall tendency of each neuron
# Like “baseline preference”
b = np.array([1, .7])
output = x @ w + b
# TODO: Apply activation function (ReLU)
# ReLU removes negatives
#Negative score → “not relevant”

#Positive score → “recommended”
def relu(x):
    return np.maximum(0, x)

final_output = relu(output)

print("Final Output:", final_output)


def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)
scores = np.array([24, 29.7])

probs = softmax(scores)

print("Probabilities:", probs)

Final Output: [24.  29.7]
Probabilities: [0.00333481 0.99666519]


## 🚀 Bonus Challenge
- Try invalid matrix multiplication and observe error
- Change shapes and test compatibility
- Visualize transformation (optional)
